#!/usr/bin/env php
<?php

use AKlump\EasyPerms\Commands\ApplyCommand;
use AKlump\EasyPerms\Commands\InitCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;

foreach ([
             __DIR__ . '/vendor/autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/../../autoload.php',
         ] as $file) {
  if (file_exists($file)) {
    $class_loader = require_once $file;
    break;
  }
}

$version = Yaml::parseFile(__DIR__ . '/.web_package/config.yml')['version'];

$application = new Application('perms', $version);
$application->add(new ApplyCommand());
$application->add(new InitCommand());
$application->setDefaultCommand('help');
$application->run();
