file_permissions:
  default: 0644
  readonly: 0444
  writable: 0666
  executable: 0744
directory_permissions:
  default: 0755
  readonly: 0555
  writable: 0777
  executable: 0755
default:
  - ../../**
readonly: [ ]
writable: [ ]
executable: [ ]
