remote:  origin
git_root:  .
master:  main
patch_prefix:  .
preserve_patch_zero:  true
do_version_commit:  true
create_tags:  patch
push_master:  yes
push_tags:  yes
version_file:  .web_package/config.yml
version: 0.0.6
